site_name: My Docs
theme:
  name: material
  logo:
  font:
    text: Roboto
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    admonition:
      note: material/pencil-circle
      tip: material/fire
      warning: fontawesome/solid/triangle-exclamation
      info: material/information-slab-circle
      abstract: material/note-edit
      example: material/lightbulb-on

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list

nav:
  - Introduction:
      - Spage A: intro/spagea.md
      - Spage B: intro/spageb.md
  - Getting Started:
      - Access: getting-started/access.md
      - Log In: getting-started/log-in.md
  - Home:
      - Overview: home/overview.md
      - Dashboard Insights: home/dashboard-insights.md
  - Personalise: []
  - Settings:
      - Overview: settings/overview.md
      - Warehouse: settings/warehouse.md
      - Taxes: settings/taxes.md
      - Prefix: settings/prefix.md
      - Users: settings/user.md
      - Roles: settings/roles.md
      - Pricing: settings/pricing.md
  - Customer & Suppliers:
      - Overview: customer-&-suppliers/overview.md
      - Introduction- Customer & Supplier: customer-&-suppliers/introduction.md
      - Other Actions: customer-&-suppliers/other-actions.md
  - Quotes:
      - Overview: quotes/overview.md
      - Introduction - Quotes: quotes/introduction-quotes.md
      - Manage Quotes: quotes/manage-quotes.md
      - Convert to Invoice: quotes/convert-to-invoice.md
      - Convert to Sales Order: quotes/convert-to-so.md
      - Other Actions for Quotes: quotes/other-actions.md
  - Items:
      - Overview: items/overview.md
      - Introduction - Item: items/introduction-item.md
      - Other Actions for Item: items/other-actions.md
  - Sales Order:
      - Overview: salesorders/overview.md
      - Introduction - Sales Order: salesorders/introduction-so.md
      - Manage Sales Order: salesorders/manage-so.md
      - Convert to Invoice: salesorders/convert-to-invoice.md
      - Convert to Purchase Order: salesorders/convert-to-po.md
      - Other Actions for Sales Order: salesorders/other-actions.md
  - Invoice:
      - Overview: invoice/overview.md
      - Introduction - Invoice: invoice/introduction-invoice.md
      - Manage Invoice: invoice/manage-invoice.md
      - Other Actions for Invoice: invoice/other-actions.md
  - Purchase Order:
      - Overview: purchaseorder/overview.md
      - Basic Function of Purchase Order: purchaseorder/basic-function-of-po.md
      - Functions in Purchase Order: purchaseorder/functions-in-po.md
      - Manage Purchase Order: purchaseorder/manage-po.md
      - Other Actions for Purchase Order: purchaseorder/other-actions.md
  - Bills:
      - Overview: bills/overview.md
      - Function of Bills: bills/function-of-bills.md
      - Manage Bills: bills/manage-bills.md
      - Other Actions: bills/other-actions.md
  - Import & Export Data:
      - Import & Export: import-export-data.md
  - Ask AI Copilot:
      - Overview: ask-ai-copilot/ai-copilot-overview.md
