site_name: My Docs
theme:
  name: material
  logo:
  font:
    text: Roboto
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    admonition:
      note: material/pencil-circle
      tip: material/fire
      warning: fontawesome/solid/triangle-exclamation
      info: material/information-slab-circle
      abstract: material/note-edit
      example: material/lightbulb-on

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  - Introduction:
      - Spage A: intro/spagea.md
      - Spage B: intro/spageb.md
  - Getting Started:
      - Access MindX Inventory: getting-started/access.md
      - Log In to MindX Inventory: getting-started/log-in.md
  - Home:
      - Overview: home/overview.md
      - Dashboard Insights: home/dashboard-insights.md
  #- Personalise: []
  - Settings:
      - Settings Overview: settings/overview.md
      - Warehouse: settings/warehouse.md
      - Taxes: settings/taxes.md
      - Prefix: settings/prefix.md
      - Users: settings/users.md
      - Roles: settings/roles.md
      - Pricing: settings/pricing.md
  - Customer & Suppliers:
      - Customer & Supplier Overview: customer-&-suppliers/overview.md
      - Introduction- Customer & Supplier: customer-&-suppliers/introduction.md
      - Other Actions for Customer & Supplier: customer-&-suppliers/other-actions.md
  - Quotes:
      - Quotes Overview: quotes/overview.md
      - Introduction - Quotes: quotes/introduction-quotes.md
      - Manage Quotes: quotes/manage-quotes.md
      - Convert to Invoice: quotes/convert-to-invoice.md
      - Convert to Sales Order: quotes/convert-to-so.md
      - Other Actions for Quotes: quotes/other-actions.md
  - Items:
      - Items Overview: items/overview.md
      - Introduction - Items: items/introduction-item.md
      - Other Actions for Items: items/other-actions.md
  - Sales Order:
      - Sales Order Overview: salesorders/overview.md
      - Introduction - Sales Orders: salesorders/introduction-so.md
      - Manage Sales Orders: salesorders/manage-so.md
      - Convert to Invoice: salesorders/convert-to-invoice.md
      - Convert to Purchase Order: salesorders/convert-to-po.md
      - Other Actions for Sales Orders: salesorders/other-actions.md
  - Invoices:
      - Invoice Overview: invoices/overview.md
      - Introduction - Invoices: invoices/introduction-invoice.md
      - Manage Invoices: invoices/manage-invoice.md
      - Other Actions for Invoices: invoices/other-actions.md
  - Purchase Order:
      - Purchase Order Overview: purchaseorder/overview.md
      - Basic Function of Purchase Orders: purchaseorder/basic-function-of-po.md
      - Functions in Purchase Orders: purchaseorder/functions-in-po.md
      - Manage Purchase Orders: purchaseorder/manage-po.md
      - Other Actions for Purchase Orders: purchaseorder/other-actions.md
  - Bills:
      - Bills Overview: bills/overview.md
      - Function in Bills: bills/function-in-bills.md
      - Manage Bills: bills/manage-bills.md
      - Other Actions for Bills: bills/other-actions.md
  - Ask AI Copilot:
      - Overview: ask-ai-copilot/ai-copilot-overview.md
