name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

permissions:
  contents: write  # Default permission for most cases
  id-token: write   # If you use OIDC tokens for deployments

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only the latest commit

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Check MkDocs Version
        run: mkdocs --version

      - name: Build Documentation
        run: mkdocs build --clean  # Ensure successful build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          mkdocs gh-deploy --force

      - name: Notify Deployment Success
        run: echo "Deployment Successful!"  # Or any notification action
